- hosts: all
  become: yes
  roles:
  - role: local-persistent-volumes

- import_playbook: ./kubespray/cluster.yml

- hosts: kube1
  become: yes
  roles:
  - role: helm
  - { role: k8s-namespace, k8s_namespace: "patroni" }
  - { role: k8s-patroni-cluster, patroni_helm_release: "patroni", k8s_namespace: "patroni" }
  - { role: postgresql-grafana }
  - { role: k8s-grafana, k8s_namespace: "patroni", grafana_helm_release: "grafana", k8s_grafana_admin_name: "test", k8s_grafana_admin_password: "AhDou1ai" }
